name: build docker image

on:
  schedule:
    - cron: "0 12 * * *"
  push:
    paths-ignore:
      - "*.md"
      - "*.txt"
      - "*.png"
  pull_request:

env:
  IMAGE_NAME: akegata/sftp-centos

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # for proper signature verification
          submodules: true # for shunit2

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: tests/shunit2

      - name: Build centos image
        run: |
          docker build . \
            --pull=true \
            --file=Dockerfile \
            --tag="$IMAGE_NAME:latest" \
            --tag="$IMAGE_NAME:centos" \
            --label="org.opencontainers.image.source=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" \
            --label="org.opencontainers.image.revision=$GITHUB_SHA" \
            --label="org.opencontainers.image.created=$(date --rfc-3339=seconds)"

      - name: Push images to Docker Hub registry
        if: github.ref == 'refs/heads/master'
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

          docker push --all-tags $IMAGE_NAME
          docker logout

      - name: Push images to GitHub registry
        if: github.ref == 'refs/heads/master'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com \
            -u ${{ github.actor }} --password-stdin

          REPONAME=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')
          TAG_CENTOS=docker.pkg.github.com/$REPONAME/centos
          docker tag $IMAGE_NAME:centos $TAG_CENTOS
          docker push $TAG_CENTOS
          docker logout docker.pkg.github.com
